routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\MainPageController::class, 'index'])->name('');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/users', [App\Http\Controllers\HomeController::class, 'allUsers'])->name('users');
Route::get('/addE', [App\Http\Controllers\HomeController::class, 'addEmployee'])->name('addE');
Route::resource('/add_employee', App\Http\Controllers\EmployeeController::class);

app/Models/AddModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AddModel extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    
    protected $table = "add_employee";
    
   
    protected $fillable = [
        'firstname',
        'lastname',
        'dateofbirth',
        'department',
    ];
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    
     protected $table = "add_employee";
    
     protected $fillable = [
        'firstname',
        'lastname',
        'dateofbirth',
        'department',
        'email',
    ];
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
//    use Notifiable;
    
    protected $table = "roles";
    
    protected $fillable = [
        'role_name',
    ];
    
    
}

app/Models/RoleUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RoleUser extends Model
{
    use HasFactory;
    
     protected $fillable = [
        'role_id', 'user_id'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\RoleUser;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'firstname' => 'required',
            'lastname' => 'required',
            'dateofbirth' => 'required',
            'department' => 'required',
            'email' =>  'required'
        ]);
       
        
       $user =  Employee::create($request->all());
       
        
         return redirect()->route('addE')
            ->with('success', 'Employee Added successfully.');
    }
    
   

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\Role;
use App\Models\RoleUser;
use App\Models\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userType = RoleUser::where("user_id", auth()->user()->id)->value('role_id'); 
        
        if($userType == 2){
            $idata =  Employee::latest()->paginate(30);
        }else{
           $idata =   Employee::where("id", auth()->user()->id)->latest()->paginate(30);
        }
     
        
        $data = ['all_emp' => $idata, 'usertype' => $userType];
        
        return view('home', $data)
                ->with('i', (request()->input('page', 1) - 1) * 50);
    }
    
    
    
    public function allUsers() {
        
        $userType = RoleUser::where("user_id", auth()->user()->id)->value('role_id'); 
        
        if($userType == 2){
            $idata =  User::latest()->paginate(30);
        }else{
           $idata =   User::where("id", auth()->user()->id)->latest()->paginate(3);
        }
        
        $data =  ['all_emp' => $idata, 'usertype' => $userType];
        
        return view('users', $data)
                ->with('i', (request()->input('page', 1) - 1) * 50);
    }
    
    
   
    
    public function addEmployee(){
        
        return view('add_employee');
    }
    
    
    
    
    
    public function create(){
        
    }
    
    
    
    
    public function update(){
        
    }
}

app/Http/Controllers/MainPageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\User;

class MainPageController extends Controller
{
    /*   THIS IS THE INDEX PAGE OF THE APPLICATION */
    
    public function index(){
        
        $data = [
            'user' => count(User::all()),
            'employee' => count(Employee::all())
        ];
        
        return view('welcome', $data);
    }
}

resources/views/add_employee.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    
                    
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> <br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    <div>
                        <a href="{{ route('home') }}" class="btn btn-danger"> Back </a>
                        <hr/>
                    </div>
                   
                    <div>
                        <h2>Add Employee</h2>
                    </div>
                    
                      <div class="card-body">
                    <form method="POST" action="{{ route('add_employee.store') }}">
                        @csrf

                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">First Name</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="" >
                                

                            </div>
                        </div>
                        
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Last Name</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="" required autofocus>

                            </div>
                        </div>
                        
                         <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Staff Email</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="email" value="" required autofocus>

                            </div>
                        </div>
                        
                        
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Date of Birth</label>

                            <div class="col-md-6">
                                <input id="dateofbirth" type="date" class="form-control" name="dateofbirth"  required autofocus>

                            </div>
                        </div>
                        
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">First Name</label>

                            <div class="col-md-6">
                                <select class="form-control" name="department"  id="department" >
                                     <option value="">Select</option>
                                      <option value="Information Technology">Information Technology</option>
                                     <option value="Human Resources">Human Resources</option>
                                      <option value="Account">Account</option>
                                       <option value="Corporate Communications">Corporate Communications</option>
                                </select>
                            </div>
                        </div>
                        
                        
                        
                        <div class="row mb-3">
                            
                            <div class="col-md-6 offset-md-5">
                                <input type="submit" value="Add Employee" class="btn btn-primary btn-sm" />
                            </div>
                        </div>
                        
                    </form>
                      </div>
                   
                   
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('List of Staff') }}</div>

                <div class="card-body">
                    
                     @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p></p>
                        </div>
                    @endif
    
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>
                          <a href="/" class="btn btn-secondary">Home <span class="fa fa-user"></span></a>
                        @if($usertype == 2)
                         <a href="{{  route('home') }}" class="btn btn-success">All Employee <span class="fa fa-user">+</span></a>
                         <a href="{{  route('addE') }}" class="btn btn-danger">Add Employee <span class="fa fa-user">+</span></a>
                         <a href="{{  route('users') }}" class="btn btn-primary">All Users <span class="fa fa-user">+</span></a>
                        @endif
                        <hr/>
                    </div>
                   
                    <div>
                       
                        @if(count($all_emp) > 0)
                        <table class="table table-responsive" id="holdings">
                            <thead>
                            <tr>
                                <th>S/n</th>
                                <th>Firstname</th>
                                 <th>Lastname</th>
                                 <th>Date of Birth</th>
                                 <th>Department</th>
                                  <th>Action</th>
                            </tr>
                            </thead>
                            
                            <tbody>
                            @foreach ($all_emp as $key => $emp)
                             <tr>
                                <td> {{ $emp->id }}</td>
                                 <td>{{ $emp->firstname }}</td>
                                 <td>{{ $emp->lastname }}</td>
                                 <td>{{ $emp->dateofbirth }}</td>
                                 <td>{{ $emp->department }}</td>
                                 <td><button class="btn btn-sm">Edit</button></td>
                            </tr>
                           
                            @endforeach
                             </tbody>
                            
                        </table>
                        @else
                        <div>Your Records have not been captured!. Please contact Human Resources</div>
                        
                        @endif
                        
                    </div>
                   
                   
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
      <link href="{{ asset('css/style.css') }}" rel="stylesheet">
      <link href="{{ asset('css/datatables.css') }}" rel="stylesheet">
      
      
      

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md  shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <h5>Holding Employee Management System</h5>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">
                                        Profile
                                    </a>
                                    
                                     <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
  
      <script src="{{ asset('js/jquery.js') }}"></script>
      <script src="{{ asset('js/datatables.min.js') }}"></script>
 

  <script>
      $(document).ready(function() {
    $('#holdings').DataTable();
} );
  </script>
</body>
</html>

resources/views/users.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('List of Users') }}</div>

                <div class="card-body">
                    
                     @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p></p>
                        </div>
                    @endif
    
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>
                          <a href="/" class="btn btn-secondary">Home <span class="fa fa-user"></span></a>
                        @if($usertype == 2)
                        <a href="{{  route('home') }}" class="btn btn-success">All Employee <span class="fa fa-user">+</span></a>
                         <a href="{{  route('addE') }}" class="btn btn-danger">Add Employee <span class="fa fa-user">+</span></a>
                         <a href="{{  route('users') }}" class="btn btn-primary">All Users <span class="fa fa-user">+</span></a>
                        @endif
                        <hr/>
                    </div>
                   
                    <div>
                       
                        @if(count($all_emp) > 0)
                        <table class="table table-responsive" id="holdings">
                            <thead>
                            <tr>
                                <th>S/n</th>
                                <th>Firstname</th>
                                 <th>email</th>
                                 <th>Date Created</th>
                            </tr>
                            </thead>
                            
                            <tbody>
                            @foreach ($all_emp as $key => $emp)
                             <tr>
                                <td> {{ $emp->id }}</td>
                                 <td>{{ $emp->name }}</td>
                                 <td>{{ $emp->email }}</td>
                                 <td>{{ $emp->created_at }}</td>
                            </tr>
                            @endforeach
                             </tbody>
                            
                        </table>
                        @else
                        <div>Your Records have not been captured!. Please contact Human Resources</div>
                        
                        @endif
                        
                    </div>
                   
                   
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection